### PR TITLE
Fix css navbar

### PR DESCRIPTION
**Pull request by DrMattG**
It is an ugly hack and only a partial fix

### CODE REVIEW

**Comment by DrMattG** [comment]
Closes https://github.com/NINAnor/ecRxiv/issues/31 but I can not access Shiny server

**Comment by anders-kolstad** [comment]
I hashed out some code that excluded /data/ patterns, since on the server all paths start with /data/

**Comment by anders-kolstad** [comment]
When running on the RStudio server, the navbar is blue and all the buttons are invisible (almost) untill you press them.

**Comment by anders-kolstad** [comment]
I switched over to usign an iframe. See #31

**Pull request merged**
